FROM    centos:centos7
ENV     container docker
RUN     yum -y install http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN     yum -y install --enablerepo=remi,remi-php72 php php-cli php-common php-pgsql php-devel php-fpm php-gd php-mbstring php-mysqlnd php-pdo php-pear php-pecl-apcu php-soap php-xml php-xmlrpc
ADD     www.conf.erb /etc/php-fpm.d/www.conf
RUN     kill -USR2 1
RUN     useradd nginx
RUN     mkdir -p /run/php-fpm
RUN     curl -sS https://getcomposer.org/installer | php -- --install-dir=/tmp
RUN     mv /tmp/composer.phar /usr/local/bin/composer
RUN     yum -y install npm
WORKDIR /var/www
EXPOSE 9000
ENTRYPOINT     php-fpm -F
