version: "3"

services:
  webserver-nginx:
    ports:
      - "8000:80"
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    volumes:
      - ../application:/var/www
      - ./nginx/log:/var/log/nginx
    links:
      - php
    depends_on:
      - php
  php:
    build:
      context: ./php
      dockerfile: Dockerfile-php-fpm
    environment:
      DB_HOST: db
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ../application:/var/www
    links:
      - db
  db:
    image: postgres:10.1
    ports:
    - "5432:15432"
    environment:
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=mysecretpassword1234"