FROM    centos:centos7
ENV     container docker
RUN yum install -y http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
RUN     yum -y update
RUN     yum install -y nginx
EXPOSE 80
ADD nginx.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT /usr/sbin/nginx -g 'daemon off;'